name: Test pipeline
on:
  push:
    branches: [ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: pip install -r test_requirements.txt

      - name: Run test
        run: py.test --cov=pycpfcnpj tests/*.py

